{
    "name": "Parking Management System",
    "icon": "static/description/icon.png",
    "version": "1.7.0",
    "depends": ["base", "mail", "account", "sale_management", "portal"],
    "data": [
        "security/ir.model.access.csv",
        "security/parking_security.xml",
        "data/parking_data.xml",
        "data/parking_notification_data.xml",
        "views/parking_menu.xml",
        "views/parking_location_views.xml",
        "views/parking_spot_views.xml",
        "views/parking_vehicle_views.xml",
        "views/parking_service_views.xml",
        "views/parking_price_template_views.xml",
        "views/parking_contract_history_views.xml",
        "views/parking_contract_views.xml",
        "views/parking_inspection_views.xml",
        "report/parking_inspection_report.xml",
        "views/parking_portal_templates.xml",
        "views/parking_checkpoint_views.xml",
        "views/parking_terms_conditions_views.xml",
        "views/parking_checkin_checkout_views.xml",
        "views/parking_vehicle_transfer_views.xml",
        "views/parking_driver_views.xml",
        "views/parking_transporter_vehicle_views.xml",
        "views/parking_transfer_type_views.xml",
        "views/parking_dashboard.xml",
        "report/contract_report.xml",
        "report/parking_report_views.xml",
        "report/parking_report_pdf.xml",
        "wizard/parking_report_wizard_views.xml",
        "wizard/parking_checkin_wizard_views.xml",
    ],
    "demo": [],
    'controllers': ['controllers/__init__.py'],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
