{
    "name": "Parking Management System",
    "icon": "static/description/icon.png",
    "version": "18.0.8.1.2",
    "depends": ["base", "mail", "account", "sale_management", "portal", "sms", "stock"],
    "data": [
        "security/parking_security.xml",
        "security/ir.model.access.csv",
        "data/parking_data.xml",
        "data/parking_notification_data.xml",
        "data/parking_messaging_data.xml",
        "data/parking_vehicle_brand_data.xml",
        "report/parking_layout.xml",
        "report/contract_report.xml",
        "views/parking_menu.xml",
        "views/parking_location_views.xml",
        "views/parking_res_company_views.xml",
        "views/parking_spot_views.xml",
        "views/parking_spot_type_views.xml",
        "views/parking_wash_views.xml",
        "views/parking_vehicle_views.xml",
        "views/parking_vehicle_brand_views.xml",
        "views/parking_service_views.xml",
        "views/parking_price_template_views.xml",
        "views/parking_contract_history_views.xml",
        "views/parking_contract_views.xml",
        "views/parking_inspection_views.xml",
        "report/parking_inspection_report.xml",
        "report/parking_handover_report.xml",
        "report/parking_statement_report.xml",
        "report/parking_qr_labels.xml",
        "views/parking_portal_templates.xml",
        "views/parking_checkpoint_views.xml",
        "views/parking_terms_conditions_views.xml",
        "views/parking_checkin_checkout_views.xml",
        "views/parking_vehicle_transfer_views.xml",
        "views/parking_driver_views.xml",
        "views/parking_transporter_vehicle_views.xml",
        "views/parking_transfer_type_views.xml",
        "views/parking_dashboard.xml",
        "views/parking_messaging_views.xml",
        "views/parking_settings_views.xml",
        "views/account_move_views.xml",
        "views/res_partner_views.xml",
        "report/parking_report_views.xml",
        "report/parking_analysis_views.xml",
        "report/parking_report_pdf.xml",
        "wizard/parking_report_wizard_views.xml",
        "wizard/parking_reception_wizard_views.xml",
        "wizard/parking_contract_charge_views.xml",
        "views/parking_attendant_views.xml",
    ],
    "demo": [],
    "assets": {
        "web.report_assets_common": [
            "parking_management/static/src/report/parking_report.scss",
        ],
        "web.assets_backend": [
            "parking_management/static/src/dashboard/parking_dashboard.scss",
            "parking_management/static/src/spot/parking_spot_card.scss",
            "parking_management/static/src/attendant/parking_attendant.scss",
            "parking_management/static/src/attendant/parking_attendant.js",
            "parking_management/static/src/attendant/parking_attendant.xml",
            "parking_management/static/src/dashboard/parking_dashboard.js",
            "parking_management/static/src/dashboard/parking_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
