services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - odoo_parking_db_data:/var/lib/postgresql/data
    networks:
      parking_net:
        ipv4_address: 172.24.0.10
  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10020:8069"
      - "20020:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2024
    volumes:
      - /opt/odoo-parking-v1/addons:/mnt/extra-addons
      - /opt/odoo-parking-v1/etc:/etc/odoo
    restart: always
    networks:
      parking_net:
        ipv4_address: 172.24.0.11
networks:
  parking_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1
volumes:
  odoo_parking_db_data:
    external: false
