[options]

; This is the password that allows database operations:

admin_passwd = 123

db_host = False

db_port = False

db_user = odoo

db_password = odoo

dbfilter = .*

addons_path = /Users/mostafahassan/odoo18/odoo-18.0/addons,/Volumes/Windows/new/saqifaa1-staging

default_productivity_apps = True

