from . import parking_location
from . import parking_spot
from . import parking_vehicle
from . import parking_service
from . import parking_price_template
from . import parking_contract
from . import parking_contract_service_line
from . import parking_contract_history
from . import parking_spot_status_log
from . import parking_vehicle_checkpoint
from . import parking_vehicle_inspection
from . import parking_terms_conditions
from . import parking_vehicle_inspection_line
from . import account_move
from . import parking_vehicle_movement
from . import parking_driver
from . import parking_transporter_vehicle
from . import parking_transfer_type
from . import parking_vehicle_transfer
from . import parking_dashboard
from . import ir_actions_report
