# -*- coding: utf-8 -*-
{
    'name': "Real Estate",
    'version': '18.0.1.0.3',
    'summary': """Real Estate, property, rental, ownership, installments, management, projects, marketing, villa, buildings, lands """,
    'description': """Real estate management system.""",
    'author': 'Neoteric Hub',
    'company': 'Neoteric Hub',
    'website': "https://www.neoterichub.com",
    'depends': ['base', 'web', 'mail', 'product', 'purchase', 'contacts', 'account', 'stock', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'data/reservation_sequence.xml',
        'data/mail_template.xml',
        'data/contract_sequence.xml',
        'data/maintenance_request_sequence.xml',
        'data/real_estate_demo_data.xml',
        'data/project_mail_templates.xml',
        'data/owner_request_mail_templates.xml',
        'views/regions_views.xml',
        'data/ir_sequence_data.xml',
        'views/installment_template_view.xml',
        # Tenant Portal Templates (must load before portal_views.xml)
        'views/tenant_portal_templates.xml',
        'views/portal_views.xml',
        'report/report_drawing_submittal_custom.xml',
        'report/report_mep_preventive_maintenance.xml',
        'report/report_material_requisition.xml',
        'report/report_low_current_maintenance.xml',
        # 'view/view_material_requisition.xml',
        'views/maintenance_views.xml',
        'views/maintenance_job_order_views.xml',
        'views/job_order_views.xml',
        'views/view_material_requisition.xml',
        'views/view_job_order_form.xml',
        'views/low_current_maintenance_views.xml',
        'views/drawing_submittal_view.xml',
        'views/owner_portal_views.xml',
        'views/main_property_views.xml',
        'views/sub_property_views.xml',
        'views/view_drawing_submittal_form.xml',
        'views/main_property_type_views.xml',
        'views/property_status.xml',
        'views/owner_message_views.xml',
        'views/property_description.xml',
        'views/partner_view.xml',
        'views/furniture_views.xml',
        'views/rental_contract_views.xml',
        'views/rental_settlement.xml',
        'views/ownership_contract.xml',
        'views/ownership_settlement.xml',
        'views/reservation_view.xml',
        'views/configuration_views.xml',
        'views/res_partner_views.xml',
        'views/view_unit_takeover_tree.xml',
        'views/res_config_settings_views.xml',
        'views/mep_maintenance_form_views.xml',
        'views/dashboard.xml', # This is your old dashboard file
        'views/dashboard_views.xml', # This is your NEW dashboard action/menu
        'report/ownership_template.xml',
        'report/rental_contracts_template.xml',
        'report/reservation_template.xml',
        'report/report_unit_handover_form_custom.xml',
        'report/report_unit_takeover_document.xml',
        'report/tenant_information_report.xml',
        'report/offer_presentation_report.xml',
        'report/contract_setup_report.xml',
        'views/offer_presentation_views.xml',
        'views/contract_setup_views.xml',
        'views/subproperty_repeat_wizard.xml',
        'views/menu_views.xml',
        # Phase 4-6: Stock Integration, Purchase Approval, Job Completion
        'data/phase_4_6_sequences.xml',
        'data/vendor_quote_sequence.xml',
        'data/vendor_quote_email_templates.xml',
        'data/phase_4_6_checklists.xml',
        'data/phase_4_6_email_templates.xml',
        'views/maintenance_job_material_views.xml',
        'views/maintenance_material_mapping_wizard_views.xml',
        'views/purchase_requisition_views.xml',
        'views/phase_4_6_menu_views.xml',
        'views/vendor_quote_views.xml',
        'views/portal_vendor_quotes.xml',
        'views/purchase_order_views.xml',
        'views/maintenance_dashboard_views.xml',
        # Owner Dashboard with ApexCharts
        'views/owner_dashboard_template.xml',
        'views/owner_my_properties_template.xml',
        'views/owner_collected_payments_template.xml',
        'views/owner_receivables_template.xml',
        'views/owner_vendor_quotes_template.xml',
        'views/owner_request_form_template.xml',
        'views/portal_my_home_override.xml',
        # 'views/job_completion_views.xml',  # Temporarily disabled
    ],
    'assets': {
        'web.assets_backend': [
            'nthub_realestate/static/src/js/apexcharts.js',
            # 'nthub_realestate/static/src/js/dashboard.js', # Old dashboard JS
            'nthub_realestate/static/src/js/realestate_dashboard.js',
            'nthub_realestate/static/src/xml/realestate_dashboard_template.xml',
            'nthub_realestate/static/src/scss/realestate_dashboard.scss',
            # Maintenance Dashboard
            'nthub_realestate/static/src/js/maintenance_dashboard.js',
            'nthub_realestate/static/src/xml/maintenance_dashboard_template.xml',
        ],
        'web.assets_frontend': [
            'nthub_realestate/static/src/js/portal.js',
            'nthub_realestate/static/src/js/owner_dashboard_charts.js',
            'nthub_realestate/static/src/scss/owner_dashboard.scss',
        ],
        'web.assets_qweb': [
            # 'nthub_realestate/static/src/xml/dashboard.xml', # Old dashboard XML
            # 'nthub_realestate/static/src/xml/realestate_dashboard_template.xml', # New dashboard XML
        ],
    },
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}